Second attempt at improved deployment names
As it turns out, $ZIPFILE and $DEBFILE are determined by CMake.

So, this builds up $DEPLOY_FILE and copies the file over before deployment.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -47,9 +47,11 @@ script:
      cd $TRAVIS_BUILD_DIR/build;
      cmake -DVSP_LIBRARY_PATH=$TRAVIS_BUILD_DIR/buildlibs -DCXX_OMP_COMPILER=/usr/local/bin/g++-9 -DC_OMP_COMPILER=/usr/local/bin/gcc-9 -DCMAKE_C_COMPILER=/usr/local/opt/llvm@7/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm@7/bin/clang++ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="~/OpenVSP_Install" ../src;
      make -j2 package;
-     ZIPFILE=$TRAVIS_BUILD_DIR/build/OpenVSP-*-MacOS_$TRAVIS_COMMIT.zip;
-     ls $ZIPFILE && (echo "ZIP CREATION SUCCESSFUL" && exit 0) || (echo "ZIP CREATION FAILED" && exit 1);
-     export DEPLOY_FILE="$ZIPFILE";
+     ZIPFILE=$TRAVIS_BUILD_DIR/build/OpenVSP-*-MacOS.zip;
+     DEPLOY_FILE=$TRAVIS_BUILD_DIR/build/OpenVSP-*-MacOS_$TRAVIS_COMMIT.zip;
+     cp $ZIPFILE $DEPLOY_FILE;
+     ls $DEPLOY_FILE && (echo "ZIP CREATION SUCCESSFUL" && exit 0) || (echo "ZIP CREATION FAILED" && exit 1);
+     export DEPLOY_FILE;
     fi
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cd $TRAVIS_BUILD_DIR/buildlibs;
@@ -58,9 +60,11 @@ script:
      cd $TRAVIS_BUILD_DIR/build;
      cmake -DCMAKE_BUILD_TYPE=Release -DVSP_CPACK_GEN=DEB -DVSP_LIBRARY_PATH=$TRAVIS_BUILD_DIR/buildlibs ../src;
      make -j2 package;
-     DEBFILE=$TRAVIS_BUILD_DIR/build/OpenVSP-*-Ubuntu-$UVER_amd64_$TRAVIS_COMMIT.deb;
-     ls $DEBFILE && (echo "DEB CREATION SUCCESSFUL" && exit 0) || (echo "DEB CREATION FAILED" && exit 1);
-     export DEPLOY_FILE="$DEBFILE";
+     DEBFILE=$TRAVIS_BUILD_DIR/build/OpenVSP-*-Linux.deb;
+     DEPLOY_FILE=$TRAVIS_BUILD_DIR/build/OpenVSP-*-Ubuntu-$UVER_amd64_$TRAVIS_COMMIT.deb;
+     cp $DEBFILE $DEPLOY_FILE;
+     ls $DEPLOY_FILE && (echo "DEB CREATION SUCCESSFUL" && exit 0) || (echo "DEB CREATION FAILED" && exit 1);
+     export DEPLOY_FILE;
     fi
 deploy:
   provider: releases
