MacOS updates to Travis build
Make Python work, use specific compilers (match prior compilers) from
homebrew, split build into libs & vsp (no SuperBuild), diagnostics.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -30,13 +30,24 @@ addons:
       - doxygen
       - graphviz
       - texlive-latex-base
+  homebrew:
+    update: true
+    packages:
+      - swig
+      - gcc@9
+      - llvm@7
 script:
   - mkdir build buildlibs;
   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
-     cd build;
-     cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="~/OpenVSP_Install" -DVSP_INSTALL_API_TEST=true ../SuperProject;
+     cd $TRAVIS_BUILD_DIR/buildlibs;
+     cmake -DCMAKE_C_COMPILER=/usr/local/opt/llvm@7/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm@7/bin/clang++ -DCMAKE_BUILD_TYPE=Release ../Libraries;
      make -j2;
-     export DEPLOY_FILE="$TRAVIS_BUILD_DIR/build/OpenVSP-prefix/src/OpenVSP-build/OpenVSP-*-MacOS.zip";
+     cd $TRAVIS_BUILD_DIR/build;
+     cmake -DVSP_LIBRARY_PATH=$TRAVIS_BUILD_DIR/buildlibs -DCXX_OMP_COMPILER=/usr/local/opt/gcc/bin/g++-9 -DC_OMP_COMPILER=/usr/local/opt/gcc/bin/gcc-9 -DCMAKE_C_COMPILER=/usr/local/opt/llvm@7/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm@7/bin/clang++ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="~/OpenVSP_Install" ../src;
+     make -j2 package;
+     ZIPFILE=$TRAVIS_BUILD_DIR/build/OpenVSP-*-MacOS.zip;
+     ls $ZIPFILE && (echo "ZIP CREATION SUCCESSFUL" && exit 0) || (echo "ZIP CREATION FAILED" && exit 1);
+     export DEPLOY_FILE="$TRAVIS_BUILD_DIR/build/OpenVSP-*-MacOS.zip";
     fi
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cd $TRAVIS_BUILD_DIR/buildlibs;
