Removes Unnecessary Semicolons from GitHub Actions Build
Just formatting changes

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -67,67 +67,70 @@ jobs:
       shell: bash
       run:   |
         mkdir build buildlibs artifacts
-        cd $GITHUB_WORKSPACE/buildlibs;
-        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DVSP_USE_SYSTEM_LIBXML2=true -DVSP_USE_SYSTEM_FLTK=true -DVSP_USE_SYSTEM_GLM=true -DVSP_USE_SYSTEM_GLEW=true -DVSP_USE_SYSTEM_CMINPACK=true -DVSP_USE_SYSTEM_CPPTEST=false ../Libraries;
-        make -j2;
-        cd $GITHUB_WORKSPACE/build;
-        cmake -DCMAKE_BUILD_TYPE=Release -DVSP_CPACK_GEN=DEB -DVSP_LIBRARY_PATH=$GITHUB_WORKSPACE/buildlibs ../src;
-        make -j2 package;
-        DEBFILE=${GITHUB_WORKSPACE}/build/OpenVSP-*-Linux.deb;
-        VSPVER=$(ls $DEBFILE | awk 'BEGIN { FS = "-" } ; { print $2 }');
-        UVER=$(lsb_release -sr);
-        DEPLOY_FILE=${GITHUB_WORKSPACE}/build/OpenVSP-${VSPVER}-Ubuntu-${UVER}_amd64_${GITHUB_SHA}.deb;
-        cp $DEBFILE $DEPLOY_FILE;
+        cd $GITHUB_WORKSPACE/buildlibs
+        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DVSP_USE_SYSTEM_LIBXML2=true -DVSP_USE_SYSTEM_FLTK=true -DVSP_USE_SYSTEM_GLM=true -DVSP_USE_SYSTEM_GLEW=true -DVSP_USE_SYSTEM_CMINPACK=true -DVSP_USE_SYSTEM_CPPTEST=false ../Libraries
+        make -j2
+        
+        cd $GITHUB_WORKSPACE/build
+        cmake -DCMAKE_BUILD_TYPE=Release -DVSP_CPACK_GEN=DEB -DVSP_LIBRARY_PATH=$GITHUB_WORKSPACE/buildlibs ../src
+        make -j2 package
+        
+        DEBFILE=${GITHUB_WORKSPACE}/build/OpenVSP-*-Linux.deb
+        VSPVER=$(ls $DEBFILE | awk 'BEGIN { FS = "-" } ; { print $2 }')
+        UVER=$(lsb_release -sr)
+        DEPLOY_FILE=${GITHUB_WORKSPACE}/build/OpenVSP-${VSPVER}-Ubuntu-${UVER}_amd64_${GITHUB_SHA}.deb
+        
+        cp $DEBFILE $DEPLOY_FILE
         cp $DEPLOY_FILE $GITHUB_WORKSPACE/artifacts
-        ls $DEPLOY_FILE && (echo "DEB CREATION SUCCESSFUL" && exit 0) || (echo "DEB CREATION FAILED" && exit 1);
-        export DEPLOY_FILE;
+        
+        ls $DEPLOY_FILE && (echo "DEB CREATION SUCCESSFUL" && exit 0) || (echo "DEB CREATION FAILED" && exit 1)
 
     - name:  Build Windows
       if: runner.os == 'Windows'
       shell: bash
       run:   |
         mkdir build buildlibs artifacts
-        cd $GITHUB_WORKSPACE\\buildlibs;
-        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -A $BUILD_ARCH ..\\Libraries;
+        cd $GITHUB_WORKSPACE\\buildlibs
+        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -A $BUILD_ARCH ..\\Libraries
 
-        cmake --build . --config Release -j 2 ;
-        cd $GITHUB_WORKSPACE\\build;
+        cmake --build . --config Release -j 2
+        cd $GITHUB_WORKSPACE\\build
 
-        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DVSP_LIBRARY_PATH=$GITHUB_WORKSPACE\\buildlibs -A $BUILD_ARCH ..\\src;
+        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DVSP_LIBRARY_PATH=$GITHUB_WORKSPACE\\buildlibs -A $BUILD_ARCH ..\\src
 
-        # -DPYTHON_INCLUDE_DIR=%PYTHON%/include ^
-        # -DPYTHON_LIBRARY=%PYTHON%/libs/python%PYTHON_VERSION%.lib ^
+        cmake --build . --target package --config Release -j 2 
 
-        cmake --build . --target package --config Release -j 2 ;
-
-        ZIPFILE=OpenVSP*.zip;
-
+        ZIPFILE=OpenVSP*.zip
         VSPVER=$(ls $ZIPFILE | awk 'BEGIN { FS = "-" } ; { print $2 }')
         WINVER=$(ls $ZIPFILE | awk 'BEGIN { FS = "-" } ; { print $3 }' | awk 'BEGIN { FS = "." } ; { print $1 }' )
-        DEPLOY_FILE=OpenVSP-${VSPVER}-${WINVER}_${GITHUB_SHA}.zip;
-        cp $ZIPFILE $DEPLOY_FILE;
+        
+        DEPLOY_FILE=OpenVSP-${VSPVER}-${WINVER}-Python${{ matrix.python-version }}_${GITHUB_SHA}.zip
+        cp $ZIPFILE $DEPLOY_FILE
         cp $DEPLOY_FILE $GITHUB_WORKSPACE\\artifacts
-        ls $DEPLOY_FILE && (echo "ZIP CREATION SUCCESSFUL" && exit 0) || (echo "ZIP CREATION FAILED" && exit 1);
-        export DEPLOY_FILE;
+        
+        ls $DEPLOY_FILE && (echo "ZIP CREATION SUCCESSFUL" && exit 0) || (echo "ZIP CREATION FAILED" && exit 1)
 
     - name:  Build MacOS
       if: runner.os == 'macos'
       shell: bash
       run:   |
         mkdir build buildlibs artifacts
-        cd $GITHUB_WORKSPACE/buildlibs;
-        cmake -DCMAKE_BUILD_TYPE=Release ../Libraries;
-        make -j2;
-        cd $GITHUB_WORKSPACE/build;
+        cd $GITHUB_WORKSPACE/buildlibs
+        cmake -DCMAKE_BUILD_TYPE=Release ../Libraries
+        make -j2
+        
+        cd $GITHUB_WORKSPACE/build
         cmake -DVSP_LIBRARY_PATH=$GITHUB_WORKSPACE/buildlibs -DCXX_OMP_COMPILER=/usr/local/bin/g++-10 -DC_OMP_COMPILER=/usr/local/bin/gcc-10 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="~/OpenVSP_Install" ../src;
-        make -j2 package;
-        ZIPFILE=${GITHUB_WORKSPACE}/build/OpenVSP-*-MacOS.zip;
+        make -j2 package
+        
+        ZIPFILE=${GITHUB_WORKSPACE}/build/OpenVSP-*-MacOS.zip
         VSPVER=$(ls $ZIPFILE | awk 'BEGIN { FS = "-" } ; { print $2 }')
-        DEPLOY_FILE=${GITHUB_WORKSPACE}/build/OpenVSP-${VSPVER}-MacOS_${GITHUB_SHA}.zip;
-        cp $ZIPFILE $DEPLOY_FILE;
+        DEPLOY_FILE=${GITHUB_WORKSPACE}/build/OpenVSP-${VSPVER}-MacOS_${GITHUB_SHA}.zip
+        
+        cp $ZIPFILE $DEPLOY_FILE
         cp $DEPLOY_FILE $GITHUB_WORKSPACE/artifacts
-        ls $DEPLOY_FILE && (echo "ZIP CREATION SUCCESSFUL" && exit 0) || (echo "ZIP CREATION FAILED" && exit 1);
-        export DEPLOY_FILE;
+        
+        ls $DEPLOY_FILE && (echo "ZIP CREATION SUCCESSFUL" && exit 0) || (echo "ZIP CREATION FAILED" && exit 1)
 
     - name: Upload Artifacts
       uses: actions/upload-artifact@v2
